# This version is only a placeholder and will be replaced at the start of each job in the init phase.
version: "{build}-{branch}"

skip_tags: false
skip_non_tags: false
skip_branch_with_pr: false

shallow_clone: false
clone_depth: 5

environment:
  global:
    APPVEYOR_RDP_PASSWORD:
      secure: KN38AnwEZQ6wMS1ktlkybV0BEvTUgnvajLAPBJWdH8I4lttpWzTkLdU+XgLoG6X//t76IbiaIdEPFKEDzgoHyY2xGIxofmS2BDtQD+I9T3o=
    APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDG7+Rf4XVbw3QUZwKR8UehNXXKuxgoLnHi4/VQ3w5CrOmJ0ANCoPsm34jJlBUM06Qkxi7LGjZs3TAKmzUKMKkG8K5y7xlHMVkYxrd9HVchrBCLCMB0SdWNZ3uqkmOtwkGCHSyYkXlzHT5qFMbxoJHsLsrXrp9UVTyOVPBZI/7lnmeLq6xofZJ7PjJA//NB0WgjU1Rlri7+Xo2/ZTUdq6i6TqX8oZHWJNCn3q3tPJ/gVU7/6FgxtArduiK8rq45uROAq1Vhhu7vXMgXZaMtzXKwhVx68w9GGLkm8e5cvey1rIaJFj3Gx7NsORwzVwwtIQ3FP1KI3qonmPvBcV/0icb
    MSVC_VERSION: 14.16.27023
    WIN_SDK_VERSION: 10.0.26624.0
    WIN_MSYS2_ROOT: C:\msys64
    WIN_MSYS2_CACHE: C:\msys64\var\cache\pacman\pkg
    WIN_OTP_PATH: C:\Program Files\erl
    BUILD_PATH: /c/projects/aeternity
    ERL_EPMD_ADDRESS: 127.0.0.1
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      OTP_VERSION: 20.1
      ERTS_VERSION: 9.1
      BUILD_STEP: build
      TEST_STEPS: ct,release
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      OTP_VERSION: 20.3
      ERTS_VERSION: 9.3
      BUILD_STEP: build
      TEST_STEPS: ct,release
      #
      #    NOTE: This job can be used as a backup to CircleCI. Only enable it temporarily when needed.
      #
      #    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      #      OTP_VERSION: 20.3.8.18
      #      ERTS_VERSION: 9.2
      #      BUILD_STEP: build
      #      TEST_STEP: ct

# We disable this for now to keep build times at a minimum,
# because we know it's not supported at the moment.
#    - OTP_VERSION: 21.2
#      ERTS_VERSION: 10.2
#      BUILD_STEP: build
#      TEST_STEP: ct

cache:
  - '%WIN_MSYS2_CACHE%'                       # msys2
  - '%LocalAppData%\NuGet\Cache'              # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache'           # NuGet v3
  - '%WIN_OTP_PATH%9.1'                       # Erlang/OTP 20.1
  - '%WIN_OTP_PATH%9.3'                       # Erlang/OTP 20.3
  - '%WIN_OTP_PATH%10.2'                      # Erlang/OTP 21.2
  - '%USERPROFILE%\.cache\rebar3'             # rebar3 cache
  - '_build\default_%ERTS_VERSION% -> %TMP%\REVISION_appveyor_%ERTS_VERSION%'   # local build files

platform: x64

matrix:
  fast_finish: false
  allow_failures:
    - OTP_VERSION: 21.2

init:
# Replaces the placeholder version with a custom format: BUILD_NUMBER-BRANCH-SHORT_GIT_SHA
  - ps: |
      if ($isWindows) {
        Update-AppveyorBuild -Version "$env:appveyor_build_number-$env:appveyor_repo_branch-$($env:appveyor_repo_commit.substring(0,7))"
        iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/ab48d6e110f2feb585b6b908a72d6e7dbfb83cb3/scripts/enable-rdp.ps1'))
        systeminfo
      }
# Attempt to ensure we don't try to convert line endings to Win32 CRLF as this will cause build to fail
  - cmd: git config --global core.autocrlf true
  - sh: git config --global core.autocrlf input
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
  - cmd: echo "%APPVEYOR_REPO_COMMIT%">"%TMP%\\REVISION_appveyor_%ERTS_VERSION%"

install:
  - cmd: '%APPVEYOR_BUILD_FOLDER%\scripts\windows\msys2_prepare.bat'
  - sh: '$APPVEYOR_BUILD_FOLDER/ci/appveyor/linux_prepare.sh'

build_script:
  - cmd: '%APPVEYOR_BUILD_FOLDER%\ci\appveyor\build.bat'
  - sh: make prod-build

after_build:
  - cmd: '%APPVEYOR_BUILD_FOLDER%\ci\appveyor\package.bat'

test_script:
  - cmd: '%APPVEYOR_BUILD_FOLDER%\ci\appveyor\test.bat'
  - sh: epmd -daemon
  - sh: make ct

after_test:
  - sh: tar cJf test_logs.txz _build/test/logs

deploy: off

on_finish:
# Set blockRdp to true to allow RDP, uses Git tag build-agent-v6.1.0%2B1300
  - ps: |
      if ($isWindows) {
        $blockRdp = $false; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/ab48d6e110f2feb585b6b908a72d6e7dbfb83cb3/scripts/enable-rdp.ps1'))
      }
# Set APPVEYOR_SSH_BLOCK to true to allow SSH access
  - sh: export APPVEYOR_SSH_BLOCK=false
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -

artifacts:
  - name: Windows Release
    path: aeternity-*.exe
  - name: Windows Release Standalone
    path: aeternity-*.zip
  - name: Test Logs (Linux)
    path: test_logs.txz
