---
peers:
    - aenode://pp_28uQUgsPcsy7TQwnRxhF8GMKU4ykFLKsgf4TwDwPMNaSCXwWV8@node2:3015
    - aenode://pp_Dxq41rJN33j26MLqryvh7AnhuZywefWKEPBiiYu2Da2vDWLBq@node3:3015
http:
    external:
        port: 3013
    internal:
        listen_address: 0.0.0.0
    cors:
        allow_domains: [""]

keys:
    peer_password: "top secret"
    dir: ./keys

chain:
    persist: true

mining:
    beneficiary: "ak_twR4h7dEcUtc2iSEDv8kB7UFJJDGiEDQCXr85C3fYF8FdVdyo"
    beneficiary_reward_delay: 2
    autostart: true
    cuckoo:
        miner:
            executable: mean15-generic
            extra_args: ""
            edge_bits: 15

fork_management:
    network_id: ae_docker
