---
peers:
    - aenode://pp$HdcpgTX2C1aZ5sjGGysFEuup67K9XiFsWqSPJs4RahEcSyF7X@node1:3015
    - aenode://pp$28uQUgsPcsy7TQwnRxhF8GMKU4ykFLKsgf4TwDwPMNaSCXwWV8@node2:3015

http:
    external:
        port: 3013
    internal:
        listen_address: 0.0.0.0

websocket:
    internal:
        listen_address: 0.0.0.0

keys:
    password: "top secret"
    dir: ./keys

chain:
    persist: true

mining:
    autostart: true
    cuckoo:
        miner:
            executable: mean16s-generic
            extra_args: ""
            node_bits: 16
